export const LEVELS_100 = [
  { requiredXP: 0, icon: "🥚", title: "The Little Egg" },
  { requiredXP: 250, icon: "🐣", title: "Babe Chick" },
  { requiredXP: 500, icon: "🐥", title: "Chicken Boi" },
  { requiredXP: 750, icon: "🐤", title: "Confused Bird" },
  { requiredXP: 1000, icon: "🐔", title: "Ultimate Chicken Boy" },
  { requiredXP: 1250, icon: "🐓", title: "Gút Morning Alarm" },
  { requiredXP: 1500, icon: "🦃", title: "Thanksgiving Dinner" },
  { requiredXP: 1750, icon: "🐸", title: "Pepe The Frog" },
  { requiredXP: 2000, icon: "🐊", title: "Swamp Monster" },
  { requiredXP: 2250, icon: "🐢", title: "Ninja Turtle" },
  { requiredXP: 2500, icon: "🦎", title: "Babe Lizard" },
  { requiredXP: 2750, icon: "🐍", title: "Danger Noodle" },
  { requiredXP: 3000, icon: "🦕", title: "Tall Boi Dino" },
  { requiredXP: 3250, icon: "🦖", title: "Tiny Hands Rex" },
  { requiredXP: 3500, icon: "🦤", title: "Extinct Dodo" },
  { requiredXP: 3750, icon: "🪿", title: "Honking Goose" },
  { requiredXP: 4000, icon: "🐧", title: "Tuxedo Bird" },
  { requiredXP: 4250, icon: "🦆", title: "Quack Quack" },
  { requiredXP: 4500, icon: "🦢", title: "Elegant Swimmer" },
  { requiredXP: 4750, icon: "🦩", title: "Pinky Stander" },
  { requiredXP: 5125, icon: "🕊️", title: "Peace Maker" },
  { requiredXP: 5500, icon: "🦜", title: "Chatty Parrot" },
  { requiredXP: 5875, icon: "🦚", title: "Show-Off Bird" },
  { requiredXP: 6250, icon: "🦉", title: "Night Watcher" },
  { requiredXP: 6625, icon: "🦅", title: "Freedom Glider" },
  { requiredXP: 7000, icon: "🦇", title: "Batman Trainee" },
  { requiredXP: 7375, icon: "🐭", title: "Little Mouse" },
  { requiredXP: 7750, icon: "🐁", title: "Fast Mouse" },
  { requiredXP: 8125, icon: "🐀", title: "Street Rat" },
  { requiredXP: 8500, icon: "🐹", title: "Wheel Runner" },
  { requiredXP: 8875, icon: "🐰", title: "Bunny Face" },
  { requiredXP: 9250, icon: "🐇", title: "Carrot Cruncher" },
  { requiredXP: 9625, icon: "🐿️", title: "Nut Hoarder" },
  { requiredXP: 10000, icon: "🦔", title: "Spiky Sonic" },
  { requiredXP: 10375, icon: "🦡", title: "Grumpy Badger" },
  { requiredXP: 10750, icon: "🦨", title: "Stinky Floof" },
  { requiredXP: 11125, icon: "🦝", title: "Trash Panda" },
  { requiredXP: 11500, icon: "🦦", title: "Water Puppy" },
  { requiredXP: 11875, icon: "🦫", title: "Dam Builder" },
  { requiredXP: 12250, icon: "🦭", title: "Chubby Seal" },
  { requiredXP: 12875, icon: "🦈", title: "Shark Doo Doo" },
  { requiredXP: 13500, icon: "🐬", title: "Ocean Acrobat" },
  { requiredXP: 14125, icon: "🐋", title: "Chubby Whale" },
  { requiredXP: 14750, icon: "🐳", title: "Water Spouter" },
  { requiredXP: 15375, icon: "🐱", title: "Kitty Face" },
  { requiredXP: 16000, icon: "🐈", title: "Meowster" },
  { requiredXP: 16625, icon: "🐈‍⬛", title: "Spooky Purr" },
  { requiredXP: 17250, icon: "🐶", title: "Puppy Face" },
  { requiredXP: 17875, icon: "🐕", title: "Good Boy" },
  { requiredXP: 18500, icon: "🦮", title: "Best Helper" },
  { requiredXP: 19125, icon: "🐕‍🦺", title: "Service Dog" },
  { requiredXP: 19750, icon: "🐩", title: "Fancy Floof" },
  { requiredXP: 20375, icon: "🐺", title: "Moon Howler" },
  { requiredXP: 21000, icon: "🦊", title: "Sly Fox" },
  { requiredXP: 21625, icon: "🐷", title: "Oink Oink" },
  { requiredXP: 22250, icon: "🐖", title: "Bacon Seed" },
  { requiredXP: 22875, icon: "🐗", title: "Angry Pig" },
  { requiredXP: 23500, icon: "🐑", title: "Cloud Walker" },
  { requiredXP: 24125, icon: "🐏", title: "Head Butter" },
  { requiredXP: 24750, icon: "🐐", title: "You are the GOAT" },
  { requiredXP: 26000, icon: "🦙", title: "Drama Llama" },
  { requiredXP: 27250, icon: "🦌", title: "Oh Deer" },
  { requiredXP: 28500, icon: "🐮", title: "Baby Moo" },
  { requiredXP: 29750, icon: "🐄", title: "Milk Maker" },
  { requiredXP: 31000, icon: "🐂", title: "Strong Ox" },
  { requiredXP: 32250, icon: "🐃", title: "Swamp King" },
  { requiredXP: 33500, icon: "🐴", title: "My Little Pony" },
  { requiredXP: 34750, icon: "🐎", title: "Neigh Neigh" },
  { requiredXP: 36000, icon: "🦓", title: "Barcode Horse" },
  { requiredXP: 37250, icon: "🐪", title: "Desert Taxi" },
  { requiredXP: 38500, icon: "🐫", title: "Double Bump" },
  { requiredXP: 39750, icon: "🦒", title: "Long Neck Boi" },
  { requiredXP: 41000, icon: "🦘", title: "Boxing Champ" },
  { requiredXP: 42250, icon: "🦥", title: "Slow Sloth" },
  { requiredXP: 43500, icon: "🐨", title: "Sleepy Koala" },
  { requiredXP: 44750, icon: "🐵", title: "Cheeky Monkey" },
  { requiredXP: 46000, icon: "🐒", title: "Banana Lover" },
  { requiredXP: 47250, icon: "🦍", title: "King Kong" },
  { requiredXP: 48500, icon: "🦧", title: "Jungle Sage" },
  { requiredXP: 49750, icon: "🐻", title: "Bear Cub" },
  { requiredXP: 52250, icon: "🐻‍❄️", title: "Ice Chiller" },
  { requiredXP: 54750, icon: "🐼", title: "Bamboo Muncher" },
  { requiredXP: 57250, icon: "🐆", title: "Spotted Sprinter" },
  { requiredXP: 59750, icon: "🐯", title: "Tiger Cub" },
  { requiredXP: 62250, icon: "🐅", title: "Striped Hunter" },
  { requiredXP: 64750, icon: "🦁", title: "King of Jungle" },
  { requiredXP: 67250, icon: "🦏", title: "Armored Unicorn" },
  { requiredXP: 69750, icon: "🦛", title: "Chunky Swimmer" },
  { requiredXP: 72250, icon: "🐘", title: "Gentle Giant" },
  { requiredXP: 74750, icon: "🦣", title: "The Giant Frozen Meat" },
  { requiredXP: 77250, icon: "🐾", title: "Mystery Beast" },
  { requiredXP: 79750, icon: "🧚", title: "Fairy Guide" },
  { requiredXP: 82250, icon: "🧝", title: "Forest Elf" },
  { requiredXP: 84750, icon: "🧜‍♀️", title: "Siren Song" },
  { requiredXP: 87250, icon: "🧛", title: "Vampire Lord" },
  { requiredXP: 89750, icon: "🧞", title: "Genie In A Bottle" },
  { requiredXP: 92250, icon: "🦄", title: "Majestic Unicorn" },
  { requiredXP: 94750, icon: "🐦‍🔥", title: "Immortal Phoenix" },
  { requiredXP: 97250, icon: "🐉", title: "Legendary Dragon🌟" },
  { requiredXP: 100000, icon: "🐔", title: "The Almighty Chicken👑" },
];

export function getLevelFromXP(xp: number): number {
  let currentLevel = 1;
  for (let i = 1; i < LEVELS_100.length; i++) {
    // @ts-ignore
    if (xp >= LEVELS_100[i].requiredXP) {
      currentLevel = i + 1;
    } else {
      break;
    }
  }
  return currentLevel;
}

export function getXPForLevel(level: number): number {
  const actualLevel = Math.max(1, Math.min(LEVELS_100.length, level));
  // @ts-ignore
  return LEVELS_100[actualLevel - 1].requiredXP;
}
