// Video Mode orchestrator — ties together subtitle interception, syncing, the
// subtitle card, and the dialogue sidebar across the video sites we support.
//
// Everything site-specific lives behind `VideoPlatform` (see platform.ts); this
// file holds only what is the same everywhere. The two exceptions are called out
// where they appear: verifying a downloaded track against the on-screen
// subtitles, and the dubbed-title hint, both of which fix Netflix-only problems.

import { installSubtitleInterceptor, uninstallSubtitleInterceptor, resetSubtitleInterceptor, requestSubtitleReplay, isSoundDescription, isAutoGeneratedTrack } from './subtitleInterceptor'
import type { SubtitleCue } from './subtitleInterceptor'
import { installSubtitleDomParser, uninstallSubtitleDomParser } from './subtitleDomParser'
import { startSubtitleSyncer, stopSubtitleSyncer, updateSyncerSavedItems, updateSyncerCues, setSyncerAutoPause, setSyncerSuspended, getCues } from './subtitleSyncer'
import { initSubtitleCard, updateSubtitleCard, destroySubtitleCard, applySubtitleCardSettings, setSubtitleCardStatus, showSubtitleNotice, showWaitingForResume, hideShadowingGap, getCurrentCue, setSubtitleCardDrag } from './subtitleCard'
import type { SeekTarget } from './subtitleCard'
import { initDialogueSidebar, updateDialogueSidebarCue, updateDialogueSidebarSavedItems, appendDialogueSidebarCue, destroyDialogueSidebar, setSidebarVisible, recentreActiveCue } from './dialogueSidebar'
import type { SavedItem, VideoModeSettings } from '../../../shared/types'
import { DEFAULT_VIDEO_MODE_SETTINGS } from '../../../shared/types'
import { platformFor } from './platform'
import type { VideoPlatform } from './platform'
import { placeYouTubeOverlays, isStripOverlaid, defaultStripPosition } from './youtubeLayout'
import { getSidebarWidth, getSidebarScrollTop, setSidebarScrollTop } from './dialogueSidebar'
import { seekToSeconds, pauseVideo, playVideo, useClosedCaptions } from './videoControl'
import { setNativeTranslationCues, clearNativeTranslationCues, hasNativeTranslations, setTranslationSource } from './cueTranslation'
import { prefetchPhonetics, clearPhoneticsCache } from '../wordPhonetics'
import { configurePacing, updatePacingConfig, handleCueEnd, resumeFromWait, isWaitingForLearner, cancelPacing } from './linePacing'
import { installVideoModeKeys, uninstallVideoModeKeys, setVideoModeKeysEnabled } from './videoModeKeys'
import { openSettingsPanel, closeSettingsPanel, refreshSettingsPanel, isSettingsPanelOpen } from './videoModeSettingsPanel'
import { showDictionaryPopoverForWord, setDictionaryCloseListener, setDictionarySaveListener, isDictionaryPopoverOpen } from '../dictionary'
import { initSavedWordTooltip, destroySavedWordTooltip } from './savedWordTooltip'

// ── State ─────────────────────────────────────────────────────────────────────

let _active = false
let _settings: VideoModeSettings = { ...DEFAULT_VIDEO_MODE_SETTINGS }
let _targetLang = 'vi'
let _savedItems: SavedItem[] = []
let _interceptorCues: SubtitleCue[] = []  // cues from network interception
let _domFallbackCues: SubtitleCue[] = []  // cues from DOM parsing
let _learningLang = 'en'

// Which site we are on. Resolved once per page: a content script never outlives
// a change of origin.
const _platform: VideoPlatform | null = platformFor()

function platform(): VideoPlatform {
  // Every path here is reached only after `isVideoSite()` said yes, so the null
  // case is unreachable; Netflix is the harmless default if that ever changes.
  return _platform ?? platformFor('netflix.com')!
}

// ── Save word helper ──────────────────────────────────────────────────────────

/**
 * Where this word was heard, for getting back to it later.
 *
 * Only filled in when the platform has a permalink worth keeping: paired with
 * the `videoTimestamp` already stored, it turns a saved word into a link back to
 * the exact moment it was spoken. Without both halves the timestamp is a number
 * nothing can act on, which is what it has been until now.
 */
function videoSourceFields(): Pick<SavedItem, 'sourceUrl' | 'sourceTitle'> {
  const fields: Pick<SavedItem, 'sourceUrl' | 'sourceTitle'> = {}
  const url = platform().permalink()
  if (url) fields.sourceUrl = url
  const title = platform().mediaTitle()
  if (title) fields.sourceTitle = title
  return fields
}

async function saveWordFromSubtitle(word: string, cue: SubtitleCue): Promise<void> {
  const item: Omit<SavedItem, 'id' | 'createdAt' | 'orphaned'> = {
    text: word,
    url: window.location.href,
    prefix: '',
    suffix: '',
    occurrenceIndex: 0,
    color: 'yellow',
    sourceContext: cue.text,
    videoTimestamp: cue.startTime,
    ...videoSourceFields(),
  }
  try {
    const saved: SavedItem = await chrome.runtime.sendMessage({ type: 'SAVE_ITEM', payload: item })
    if (saved) registerSavedItem(saved)
  } catch {
    // sendMessage failure — extension reloaded or no background
  }
}

/** Drop a word from the library, and from the highlighting, straight away. */
async function unsaveWord(word: string): Promise<void> {
  const key = word.toLowerCase()
  const doomed = _savedItems.filter(i => i.text.toLowerCase() === key)
  if (doomed.length === 0) return

  _savedItems = _savedItems.filter(i => i.text.toLowerCase() !== key)
  updateSubtitleCard(getCurrentCue(), _savedItems)
  updateDialogueSidebarSavedItems(_savedItems)
  updateSyncerSavedItems(_savedItems)

  for (const item of doomed) {
    await chrome.runtime.sendMessage({ type: 'DELETE_ITEM', payload: item.id }).catch(() => { })
  }
}

/** Change the deck colour of an already-saved word, from the hover tooltip. */
async function changeSavedWordColor(word: string, color: SavedItem['color']): Promise<void> {
  const key = word.toLowerCase()
  const changed = _savedItems.filter(i => i.text.toLowerCase() === key)
  if (changed.length === 0) return

  _savedItems = _savedItems.map(i => i.text.toLowerCase() === key ? { ...i, color } : i)
  updateSubtitleCard(getCurrentCue(), _savedItems)
  updateDialogueSidebarSavedItems(_savedItems)
  updateSyncerSavedItems(_savedItems)

  for (const item of changed) {
    await chrome.runtime.sendMessage({ type: 'UPDATE_ITEM', payload: { ...item, color } }).catch(() => { })
  }
}

/** Fold a newly saved word into the live library so it highlights at once. */
function registerSavedItem(item: SavedItem): void {
  if (_savedItems.some(existing => existing.id === item.id)) return
  _savedItems = [..._savedItems, item]
  updateSubtitleCard(getCurrentCue(), _savedItems)
  updateDialogueSidebarSavedItems(_savedItems)
  updateSyncerSavedItems(_savedItems)
}

// ── Enable / Disable ──────────────────────────────────────────────────────────

export async function enableVideoMode(
  settings: VideoModeSettings,
  savedItems: SavedItem[],
  targetLang = 'vi',
  learningLang = 'en',
): Promise<void> {
  if (_active) disableVideoMode()
  _active = true
  _settings = { ...settings }
  _targetLang = targetLang
  _learningLang = learningLang
  _savedItems = savedItems

  // Build the UI up front, before any cue exists. Deferring this until a track
  // arrives meant that if interception found nothing the user saw no card, no
  // sidebar, and no native subtitles either — Video Mode looked broken with no
  // way to tell why.
  platform().installLayout()
  setDictionaryCloseListener(onDictionaryClosed)
  setDictionarySaveListener(registerSavedItem)
  initSavedWordTooltip({ onChangeColor: changeSavedWordColor, onDelete: unsaveWord })
  setTranslationSource(_settings.translationSource)
  installPacing()
  installKeys()
  buildUi()
  syncLayoutMetrics()
  setSubtitleCardStatus(waitingStatus())

  // Install subtitle interceptor (network)
  installSubtitleInterceptor(
    (cues) => {
      _interceptorCues = cues
      // The DOM scraper deliberately keeps running on Netflix: it is the only
      // source guaranteed to be for this episode, so it verifies what we loaded.
      _verified = false
      _verifyHits = 0
      _verifyMisses = 0
      onCuesReady(cues)
    },
    {
      targetLang: _targetLang,
      learningLang: _learningLang,
      onTranslationCues: (cues) => {
        setNativeTranslationCues(cues)
        // Rebuild so lines already rendered swap machine output for the site's.
        if (_interceptorCues.length > 0) onCuesReady(_interceptorCues)
        else updateSubtitleCard(getCurrentCue(), _savedItems)
      },
    },
  )

  // Install DOM fallback (fires for each visible cue when interception misses)
  installSubtitleDomParser(onDomCue, platform().nativeSubtitleSelectors)

  watchForTitleChange()
  listenForDubMismatch()
  listenForAdBreaks()

  // If cues already available (e.g. re-enable after toggle), start immediately
  if (_interceptorCues.length > 0) {
    onCuesReady(_interceptorCues)
  }
}

function onDomCue(cue: SubtitleCue) {
  if (!_active || _adPlaying) return
  if (_interceptorCues.length > 0) {
    if (platform().verifiesAgainstNative) verifyAgainstNative(cue)
    return
  }
  if (_settings.hideSoundEffects && isSoundDescription(cue.text)) return
  if (_domFallbackCues.some(c => c.text === cue.text)) return
  _domFallbackCues.push(cue)
  onFirstCue()
  // The DOM parser has no lookahead, so each cue is both "the current one" and
  // a new sidebar row.
  setSubtitleCardStatus(null)
  updateSubtitleCard(cue, _savedItems)
  appendDialogueSidebarCue(cue)
}

/**
 * How much of the screen the player gives up to the subtitle strip.
 *
 * Deliberately *not* the strip's measured height. The picture is pillarboxed —
 * bounded by the height available, not the width — so following the strip line
 * by line resized the picture on every sentence. Reserving a steady band
 * instead means the video is laid out once and left alone, while the strip
 * still grows and shrinks freely inside it: shorter lines simply leave black
 * space, which is indistinguishable from the letterbox already there.
 *
 * Sized for two lines of dialogue plus two of translation, the toolbar row, and
 * padding — enough that a line overflowing into the picture is rare.
 */
function reservedStripHeight(): number {
  return Math.round(_settings.subtitleFontSize * 4.44 + 66)
}

// Keeps the player inset in step with the sidebar and the reserved band.
function syncLayoutMetrics(): void {
  platform().setLayoutMetrics(getSidebarWidth(), reservedStripHeight())
}

/**
 * Let the learner drag the dialogue, but only where it floats over the picture.
 *
 * Which is a property of the current layout, not of the site: on YouTube the
 * strip drops back to a fixed band when the player subtree is being rebuilt, and
 * offering a drag then would move something that is about to be repositioned.
 */
function syncStripDrag(): void {
  const overlaid = _platform?.id === 'youtube' && isStripOverlaid()
  setSubtitleCardDrag({
    enabled: overlaid,
    // Falls back to a spot measured off the player's own controls, so the
    // scrubber is never buried under the dialogue on first use.
    position: overlaid ? _settings.stripPosition ?? defaultStripPosition() : null,
    widthPct: _settings.stripWidthPct,
    onGeometryChange: ({ position, widthPct }) =>
      applySettingsPatch({ stripPosition: position, stripWidthPct: widthPct }),
  })
}

// ── Pacing, keys, settings panel ──────────────────────────────────────────────

function applyPacingConfig(): void {
  updatePacingConfig({
    repeat: _settings.repeat,
    endOfLinePause: _settings.endOfLinePause,
    shadowGapFactor: _settings.shadowGapFactor,
  })
}

function installPacing(): void {
  configurePacing(
    {
      repeat: _settings.repeat,
      endOfLinePause: _settings.endOfLinePause,
      shadowGapFactor: _settings.shadowGapFactor,
    },
    {
      // A shadowing gap announces itself by the film simply stopping; a label
      // flashing on and off every line was more noise than help.
      onGapStart: () => { },
      onGapEnd: hideShadowingGap,
      onWaitStart: showWaitingForResume,
      onWaitEnd: hideShadowingGap,
    },
  )
}

function installKeys(): void {
  setVideoModeKeysEnabled(_settings.keyboardShortcuts)
  installVideoModeKeys({
    prevLine: () => seekByCue('prev'),
    nextLine: () => seekByCue('next'),
    replayLine: () => seekByCue('replay'),
    toggleTranslation: () => {
      applySettingsPatch({ showTranslation: !_settings.showTranslation })
    },
    resume: () => {
      if (!isWaitingForLearner()) return false
      resumeFromWait()
      return true
    },
  })
}

function toggleSettingsPanel(anchor: HTMLElement): void {
  if (isSettingsPanelOpen()) {
    closeSettingsPanel()
    return
  }
  openSettingsPanel(anchor, _settings, (patch) => {
    applySettingsPatch(patch)
    refreshSettingsPanel(_settings)
  })
}

/**
 * Apply a settings change locally *and* persist it, so the popup, the panel and
 * the running overlay never disagree about what is on.
 */
function applySettingsPatch(patch: Partial<VideoModeSettings>): void {
  applyVideoModeSettings({ ..._settings, ...patch })
  void chrome.runtime.sendMessage({
    type: 'SAVE_VIDEO_MODE_SETTINGS',
    payload: { settings: _settings },
  }).catch(() => { /* background asleep — the live state is still correct */ })
}

// ── Dubbed titles ─────────────────────────────────────────────────────────────

// The MAIN world reports when the audio language matches the subtitle language
// but the subtitle track is the ordinary translation rather than the CC one.
// For a dub those are separate scripts, so the subtitle never quite matches
// what is spoken — accurate, but useless to read along with.
let _dubHintInstalled = false

function listenForDubMismatch() {
  if (_dubHintInstalled) return
  _dubHintInstalled = true
  window.addEventListener('message', (e: MessageEvent) => {
    if (e.source !== window || !_active) return
    const data = e.data as { type?: string; ccName?: string } | null
    if (data?.type !== 'ELEZONE_SUBTITLE_HINT') return
    showSubtitleNotice({
      text: 'This title is dubbed, so the subtitles are a separate translation and won\'t match the spoken lines.',
      actionLabel: `Use ${data.ccName ?? 'CC'}`,
      onAction: useClosedCaptions,
    })
  })
}

// ── Ad breaks ─────────────────────────────────────────────────────────────────
//
// YouTube plays ads through the same <video> element, so `currentTime` silently
// starts describing the advert instead of the film. Nothing downstream can tell:
// the syncer would show a line from minute one, and the pacing engine would
// pause — or seek — inside the ad. The MAIN world watches for this and we simply
// stop reading the clock until it passes. We never skip or block an ad.

let _adPlaying = false
let _adListenerInstalled = false

function listenForAdBreaks() {
  if (_adListenerInstalled) return
  _adListenerInstalled = true
  window.addEventListener('message', (e: MessageEvent) => {
    if (e.source !== window || !_active) return
    const data = e.data as { type?: string; ad?: boolean; noCaptions?: boolean } | null
    if (data?.type !== 'ELEZONE_VIDEO_STATE') return

    // Nothing on this video is in the language being studied. Most of YouTube
    // is like that, so treat it as ordinary rather than as a failure: take the
    // UI back down and leave the page exactly as we found it. The page watcher
    // brings Video Mode back for the next video.
    if (data.noCaptions) {
      if (_active && getCues().length === 0) {
        console.info('[EleZone] Video Mode: nothing to study on this video, standing down')
        disableVideoMode()
      }
      return
    }

    if (typeof data.ad !== 'boolean' || data.ad === _adPlaying) return
    _adPlaying = data.ad
    setSyncerSuspended(_adPlaying)
    // Whichever way it went, any half-finished repeat or shadowing gap was
    // counted against a timeline that wasn't the video's.
    cancelPacing()
    setSubtitleCardStatus(
      _adPlaying ? 'Ad playing — subtitles resume afterwards.'
        : getCues().length > 0 ? null
          : waitingStatus()
    )
  })
}

// ── Verifying the loaded track against Netflix's own subtitles ────────────────
//
// A downloaded track can be for the wrong episode: Netflix prefetches the next
// one, and a track picked up by sniffing responses carries nothing that says
// which title it belongs to. Two episodes of a series run about the same
// length, so a duration check won't catch it either — the only trustworthy
// reference is what Netflix itself is drawing on screen right now.
//
// So the DOM scraper keeps running even after a real track loads, and every
// native line is looked up in what we loaded. Lines that never match mean the
// track is simply wrong.

let _verified = false
let _verifyHits = 0
let _verifyMisses = 0

const MIN_VERIFY_LENGTH = 8   // shorter lines match by coincidence
const MISSES_BEFORE_REJECT = 6
const HITS_BEFORE_TRUSTED = 3

function normalise(text: string): string {
  return text.toLowerCase().replace(/[^\p{L}\p{N} ]/gu, '').replace(/\s+/g, ' ').trim()
}

function verifyAgainstNative(nativeCue: SubtitleCue) {
  if (_verified) return

  // Netflix still draws sound descriptions even when we hide them, so they can
  // never be found in our list — they say nothing about whether the track fits.
  if (isSoundDescription(nativeCue.text)) return

  const target = normalise(nativeCue.text)
  if (target.length < MIN_VERIFY_LENGTH) return

  // Netflix renders its own (unmerged) cues, so a native line is typically a
  // substring of one of ours.
  const match = getCues().find(c => {
    const mine = normalise(c.text)
    return mine === target || mine.includes(target) || target.includes(mine)
  })

  if (!match) {
    _verifyMisses++
    if (_verifyMisses >= MISSES_BEFORE_REJECT && _verifyHits === 0) {
      rejectLoadedTrack()
    }
    return
  }

  _verifyHits++
  _verifyMisses = 0
  if (_verifyHits >= HITS_BEFORE_TRUSTED) {
    console.info("[EleZone] loaded track verified against Netflix's own subtitles")
    _verified = true
  }
}

// Nothing on screen matched what we loaded — better to scrape the DOM, which is
// always right, than to keep showing another episode's dialogue.
function rejectLoadedTrack() {
  console.warn(
    `[EleZone] none of the last ${MISSES_BEFORE_REJECT} on-screen subtitles appear in the ` +
    'loaded track — discarding it (wrong episode or wrong track) and scraping the player instead'
  )
  _interceptorCues = []
  _domFallbackCues = []
  _verifyMisses = 0
  resetSubtitleInterceptor()
  stopSubtitleSyncer()
  destroyDialogueSidebar()
  buildUi()
  updateSubtitleCard(null, _savedItems)
  setSubtitleCardStatus(waitingStatus())
}

function waitingStatus(): string {
  return `Waiting for subtitles — make sure they are turned on in the ${platform().label} player.`
}

// Auto-generated captions are worth reading but not worth trusting: no speaker
// labels, punctuation guessed, and words the recogniser simply got wrong. Say so
// once per track rather than leaving the learner to wonder why a line is odd.
let _asrNoticeShownFor = ''

function noteAutoGeneratedTrack(): void {
  if (!isAutoGeneratedTrack()) return
  const key = platform().mediaKey() ?? location.href
  if (_asrNoticeShownFor === key) return
  _asrNoticeShownFor = key
  showSubtitleNotice({
    text: 'These subtitles are auto-generated, so some words and sentence breaks will be wrong.',
  })
}

// Native subtitles stay visible until we actually have something to draw, so a
// failure to find a track degrades to the plain site rather than a blank screen.
function onFirstCue() {
  platform().hideNativeSubtitles()
}

// ── Dictionary lookups ────────────────────────────────────────────────────────

// Looking a word up is a deliberate stop to study, so hold the film there and
// pick it back up when the popover is dismissed.
let _resumeAfterLookup = false

function lookupWord(word: string, cue: SubtitleCue) {
  const video = document.querySelector<HTMLVideoElement>('video')
  if (video && !video.paused) {
    _resumeAfterLookup = true
    pauseVideo()
  }
  const source = videoSourceFields()
  void showDictionaryPopoverForWord(word, cue.text, cue.startTime, {
    url: source.sourceUrl,
    title: source.sourceTitle,
  })
}

function onDictionaryClosed() {
  // Opening a popover closes the previous one first, so clicking a second word
  // fires this too. Defer a tick: only a close with nothing reopened resumes.
  setTimeout(() => {
    if (isDictionaryPopoverOpen() || !_resumeAfterLookup) return
    _resumeAfterLookup = false
    playVideo()
  }, 0)
}

// Jump the video to the previous / current / next line. The cue list is the
// source of truth rather than a fixed time offset, so a replay always lands on
// the start of the sentence being shown.
function seekByCue(target: SeekTarget) {
  const current = getCurrentCue()
  if (!current) return

  const cues = getCues()
  const at = cues.findIndex(c => c.index === current.index)
  // The DOM fallback has no full list — replay is the only meaningful move.
  const neighbour = at === -1 ? undefined : cues[target === 'prev' ? at - 1 : at + 1]

  const dest = target === 'replay' ? current : neighbour
  if (!dest) return
  cancelPacing()
  seekToSeconds(dest.startTime)
}

function buildUi() {
  if (!document.getElementById('elezone-subtitle-card')) {
    initSubtitleCard({
      onSaveWord: (word, cue) => { void saveWordFromSubtitle(word, cue) },
      onLookupWord: lookupWord,
      onToggleSidebar: () => applySettingsPatch({ sidebarVisible: !_settings.sidebarVisible }),
      sidebarVisible: _settings.sidebarVisible,
      showTranslation: _settings.showTranslation,
      fontSize: _settings.subtitleFontSize,
      targetLang: _targetLang,
      phoneticsUnderWords: _settings.phoneticsUnderWords,
      learningLang: _learningLang,
    })
  }
  if (!document.getElementById('elezone-dialogue-sidebar')) {
    initDialogueSidebar({
      cues: [],
      savedItems: _savedItems,
      onLookup: lookupWord,
      onSave: (word, cue) => { void saveWordFromSubtitle(word, cue) },
      onSeek: cancelPacing,
      onSeekLine: seekByCue,
      onOpenSettings: toggleSettingsPanel,
      onUnsave: (word) => { void unsaveWord(word) },
      showTranslation: _settings.showTranslation,
      targetLang: _targetLang,
      collapsed: !_settings.sidebarVisible,
      onLayoutChange: syncLayoutMetrics,
    })
  }
  installFullscreenReparent()
  reparentOverlays()
  syncLayoutMetrics()
}

// ── Fullscreen ────────────────────────────────────────────────────────────────

// In fullscreen the browser only paints the fullscreen element's subtree, so an
// overlay parented to <body> vanishes the moment the user hits the fullscreen
// button — which is how most people watch. Re-parent the overlays into whatever
// element currently owns the screen.
const OVERLAY_IDS = ['elezone-subtitle-card', 'elezone-dialogue-sidebar']

function reparentOverlays() {
  // Moving a node detaches it, which zeroes the scroll offset of anything
  // scrollable inside — the dialogue list would jump back to the first line
  // every time the viewer went fullscreen.
  const scroll = getSidebarScrollTop()

  // YouTube puts the overlays into the page's own flow, beside and below the
  // player, so out of fullscreen there is nothing to re-parent to <body>. It
  // also re-renders the recommendations column as more videos load, which
  // orphans the sidebar — hence running this on a timer, not just on events.
  if (_platform?.id === 'youtube' && placeYouTubeOverlays()) {
    setSidebarScrollTop(scroll)
    syncStripDrag()
    return
  }

  const target = document.fullscreenElement ?? document.body
  const stale = OVERLAY_IDS
    .map(id => document.getElementById(id))
    .filter((el): el is HTMLElement => !!el && el.parentElement !== target)
  if (stale.length === 0) return

  for (const el of stale) target.appendChild(el)
  setSidebarScrollTop(scroll)
}

let _fullscreenHooked = false

function onFullscreenChange() {
  reparentOverlays()
  // The sidebar changes width crossing this boundary — a page column one side,
  // a fixed panel the other — and the strip is inset by exactly that width.
  // Without re-measuring here the inset stays wrong until the next tick.
  syncLayoutMetrics()

  // And it changes height, which the saved scroll offset cannot express: the
  // list is as tall as the picture on one side and as tall as the screen on the
  // other, so the same offset centres a different line. Re-centre on the line
  // actually playing — after the browser has laid the new size out, since the
  // sums depend on the list's height.
  requestAnimationFrame(() => requestAnimationFrame(recentreActiveCue))
}

function installFullscreenReparent() {
  if (_fullscreenHooked) return
  _fullscreenHooked = true
  document.addEventListener('fullscreenchange', onFullscreenChange)
  document.addEventListener('webkitfullscreenchange', onFullscreenChange)
}

// How many lines ahead to fetch phonetics for while the learner is still on
// the current one — enough to stay ahead of normal reading pace without
// firing lookups for dialogue that's minutes away and may never be reached
// (a seek).
const PHONETICS_PREFETCH_LINES = 3

function onCueChange(state: { currentCueIndex: number; currentCue: SubtitleCue | null }) {
  updateSubtitleCard(state.currentCue, _savedItems)
  updateDialogueSidebarCue(state.currentCueIndex)

  if (_settings.phoneticsUnderWords && _learningLang.toLowerCase().startsWith('en') && state.currentCueIndex >= 0) {
    // Only reachable with a known cue list (the DOM fallback calls
    // updateSubtitleCard directly and never goes through the syncer), so
    // there's always a real lookahead here — no separate fallback branch.
    const cues = getCues()
    const upcoming = cues.slice(state.currentCueIndex + 1, state.currentCueIndex + 1 + PHONETICS_PREFETCH_LINES)
    const words = upcoming.flatMap(c => c.text.match(/\S+/g) ?? [])
      .map(w => w.replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, ''))
      .filter(Boolean)
    if (words.length > 0) prefetchPhonetics(words)
  }
}

/**
 * The cue list as the learner sees it. Kept separate from the parsed track so
 * the setting can be flipped without re-downloading anything, and re-indexed
 * because both the syncer and the sidebar address cues by position.
 */
function visibleCues(cues: SubtitleCue[]): SubtitleCue[] {
  if (!_settings.hideSoundEffects) return cues
  return cues
    .filter(cue => !isSoundDescription(cue.text))
    .map((cue, index) => ({ ...cue, index }))
}

function onCuesReady(rawCues: SubtitleCue[]) {
  if (!_active || rawCues.length === 0) return
  const cues = visibleCues(rawCues)
  if (cues.length === 0) return

  console.info(
    `[EleZone] Video Mode: loaded ${cues.length} subtitle cues` +
    (hasNativeTranslations()
      ? ` (translation from ${platform().label} subtitles)`
      : ' (machine translation)')
  )
  onFirstCue()
  setSubtitleCardStatus(null)
  buildUi()
  noteAutoGeneratedTrack()

  // Rebuild the sidebar with the full list. A richer track can arrive after the
  // first one (Netflix fetches forced-narrative subs before the full dialogue
  // list), so replace rather than leave a stale, shorter cue list.
  destroyDialogueSidebar()
  initDialogueSidebar({
    cues,
    savedItems: _savedItems,
    onLookup: lookupWord,
    onSave: (word, cue) => { void saveWordFromSubtitle(word, cue) },
    onSeek: cancelPacing,
    onSeekLine: seekByCue,
    onOpenSettings: toggleSettingsPanel,
    onUnsave: (word) => { void unsaveWord(word) },
    showTranslation: _settings.showTranslation,
    targetLang: _targetLang,
    collapsed: !_settings.sidebarVisible,
    onLayoutChange: syncLayoutMetrics,
  })
  reparentOverlays()
  syncLayoutMetrics()

  // Land on the line that is playing right now. The syncer would get there on
  // its own next frame, but rebuilding the list (which happens again when the
  // translation track lands) resets it to the top, and starting from the top of
  // a two-hour film is a long way from where the viewer actually is.
  const playing = getCurrentCue()
  if (playing) {
    const at = cues.findIndex(c => c.startTime <= playing.startTime && c.endTime >= playing.startTime)
    if (at >= 0) updateDialogueSidebarCue(at)
  }

  // Start syncer
  updateSyncerCues(cues)
  applyPacingConfig()
  startSubtitleSyncer(cues, _savedItems, {
    autoPause: _settings.pauseOnSavedWord,
    onCueChange,
    onCueEnd: handleCueEnd,
    onSavedWordHit: (word) => {
      console.info(`[EleZone] Auto-paused on saved word: ${word}`)
    },
  })
}

export function disableVideoMode(): void {
  _active = false
  stopSubtitleSyncer()
  uninstallSubtitleInterceptor()
  uninstallSubtitleDomParser()
  destroySubtitleCard()
  destroyDialogueSidebar()
  platform().showNativeSubtitles()
  platform().removeLayout()
  setSyncerSuspended(false)
  _adPlaying = false
  setDictionaryCloseListener(null)
  setDictionarySaveListener(null)
  destroySavedWordTooltip()
  closeSettingsPanel()
  cancelPacing()
  uninstallVideoModeKeys()
  _resumeAfterLookup = false
  clearNativeTranslationCues()
  clearPhoneticsCache()
  _domFallbackCues = []
  if (_urlWatch !== null) {
    clearInterval(_urlWatch)
    _urlWatch = null
  }
}

export function isVideoModeActive(): boolean {
  return _active
}

// ── Episode changes ───────────────────────────────────────────────────────────

// Both sites move between videos without a page load, so nothing would
// otherwise clear the previous title's cues — the sidebar would keep showing
// the wrong dialogue. Polling the URL is cheap and, unlike patching
// history.pushState, doesn't collide with the read-aloud SPA guard.
let _urlWatch: number | null = null

function watchForTitleChange() {
  if (_urlWatch !== null) return
  let lastUrl = location.href
  _urlWatch = window.setInterval(() => {
    // Cheap self-heal: both sites re-render around the player — Netflix after a
    // fullscreen transition, YouTube whenever it loads more recommendations —
    // which leaves the overlays parented to a node that is no longer on screen.
    if (_active) {
      reparentOverlays()
      syncLayoutMetrics()
    }
    if (location.href === lastUrl) return
    lastUrl = location.href
    if (!_active) return
    // Left the player entirely (browse, a title page, search). Tearing down is
    // the page watcher's job — rebuilding here would put the strip and sidebar
    // over a page that has no dialogue at all.
    if (!isPlaybackPage()) return
    _interceptorCues = []
    _domFallbackCues = []
    resetSubtitleInterceptor()
    clearNativeTranslationCues()
    clearPhoneticsCache()
    _verified = false
    _verifyHits = 0
    _verifyMisses = 0
    // The MAIN world clears its cache on the same URL change; ask it for the
    // new episode's tracks once it has them.
    requestSubtitleReplay(_targetLang, _learningLang)
    stopSubtitleSyncer()
    destroyDialogueSidebar()
    platform().showNativeSubtitles()
    buildUi()
    setSubtitleCardStatus(waitingStatus())
    updateSubtitleCard(null, _savedItems)
    installSubtitleDomParser(onDomCue, platform().nativeSubtitleSelectors)
  }, 1000)
}

// ── Settings updates (from popup toggles) ─────────────────────────────────────

export function applyVideoModeSettings(settings: VideoModeSettings): void {
  const prev = _settings
  _settings = { ...settings }
  if (!_active) return

  setSidebarVisible(_settings.sidebarVisible)
  syncLayoutMetrics()
  setSyncerAutoPause(_settings.pauseOnSavedWord)
  setTranslationSource(_settings.translationSource)
  setVideoModeKeysEnabled(_settings.keyboardShortcuts)
  applyPacingConfig()
  applySubtitleCardSettings({
    showTranslation: _settings.showTranslation,
    fontSize: _settings.subtitleFontSize,
    sidebarVisible: _settings.sidebarVisible,
    phoneticsUnderWords: _settings.phoneticsUnderWords,
    learningLang: _learningLang,
  })
  // Re-render the strip so the change lands on the line already on screen.
  updateSubtitleCard(getCurrentCue(), _savedItems)

  // These four change the cue list itself or how every row renders, and the
  // sidebar builds its rows up front — a restyle isn't enough.
  if (
    prev.showTranslation !== _settings.showTranslation ||
    prev.translationSource !== _settings.translationSource ||
    prev.hideSoundEffects !== _settings.hideSoundEffects ||
    prev.phoneticsUnderWords !== _settings.phoneticsUnderWords
  ) {
    if (_interceptorCues.length > 0) onCuesReady(_interceptorCues)
  }
}

// ── Detect if current site is a video platform ────────────────────────────────

export function isVideoSite(hostname = window.location.hostname): boolean {
  return platformFor(hostname) !== null
}

/**
 * Whether this URL is a page that actually plays something.
 *
 * Being on a video *site* is not enough: Netflix autoplays trailers on /browse
 * and /title, and YouTube plays them on the home feed, so a bare "is there a
 * <video>?" test turns the whole UI on over a grid of thumbnails — and, since
 * the strip and sidebar take space from the page, mangles its layout too.
 */
export function isPlaybackPage(url = window.location.href): boolean {
  return _platform?.isPlaybackPage(url) ?? false
}

/**
 * What is playing right now, or null when nothing is.
 *
 * The page watcher keys off this rather than a plain on-a-player-page test, so
 * that moving to another video is a distinct event. That matters because Video
 * Mode can shut itself down mid-page — a video with no subtitles in the language
 * being studied — and would otherwise never come back for the next one.
 */
export function playbackMediaKey(): string | null {
  if (!isPlaybackPage()) return null
  return _platform?.mediaKey() ?? 'playing'
}

// ── Wait for video element then try to init ───────────────────────────────────

/** Resolves once a <video> exists, or false if none turns up in time. */
export function waitForVideo(timeoutMs = 30_000): Promise<boolean> {
  if (document.querySelector('video')) return Promise.resolve(true)
  return new Promise(resolve => {
    let settled = false
    const finish = (found: boolean) => {
      if (settled) return
      settled = true
      observer.disconnect()
      clearTimeout(timer)
      resolve(found)
    }
    const observer = new MutationObserver(() => {
      if (document.querySelector('video')) finish(true)
    })
    observer.observe(document.documentElement, { childList: true, subtree: true })
    const timer = setTimeout(() => finish(false), timeoutMs)
  })
}
